name: difusco
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.0=py37hd667e15_1
  - cpuonly=1.0=0
  - dataclasses=0.8=pyh6d0b6a4_7
  - freetype=2.11.0=h70c0345_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.2.0
    - beautifulsoup4==4.11.1
    - cachetools==5.2.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cycler==0.11.0
    - cython==0.29.33
    - deprecated==1.2.13
    - docker-pycreds==0.4.0
    - filelock==3.9.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - gdown==4.6.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.1
    - idna==3.4
    - imageio==2.24.0
    - importlib-metadata==6.0.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lightning-utilities==0.5.0
    - lkh==1.1.1
    - logzero==1.7.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - multidict==6.0.4
    - networkx==2.6.3
    - numpy>=1.21.0
    - oauthlib==3.2.2
    - opencv-python==4.7.0.68
    - packaging==23.0
    - pathtools==0.1.2
    - pickle5==0.0.12
    - pillow==9.4.0
    - protobuf==3.20.1
    - psutil==5.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pyconcorde @ git+https://github.com/jvkersch/pyconcorde
    - pyparsing==3.0.9
    - pyrss2gen==1.1
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-sat==0.1.7.dev25
    - pytorch-lightning==1.7.7
    - pyyaml==6.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sentry-sdk==1.13.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - tabulate==0.8.10
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - threadpoolctl==3.1.0
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - torch==1.11.0+cu113
    - torchaudio==0.11.0+cu113
    - torchvision==0.12.0+cu113
    - --find-links https://data.pyg.org/whl/torch-1.11.0+cu113.html
    - pyg-lib==0.1.0
    - torch-scatter==2.0.9
    - torch-cluster==1.6.0
    - torch-sparse==0.6.15
    - torch-spline-conv==1.2.1
    - torch-geometric==2.2.0
    - torchmetrics==0.11.0
    - tqdm==4.64.1
    - tsplib95==0.7.1
    - urllib3==1.26.14
    - wandb==0.13.9
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - yarl==1.8.2
    - zipp==3.11.0
